<?php
/** @var \Zero1\Base\Block\Adminhtml\Messages $block */
//die(__FILE__);
$messages = $block->getMessages();
?>
<?php if(!empty($messages)): ?>
    <?php foreach ($messages as $message) : ?>
            <div class="message message-success success">
                <div data-ui-id="messages-message-success"><?= $message;?></div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>